name: Convert to srs

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/create-srs.yml
      - src/**
      - convert.py
  # schedule:
  #   - cron: '33 */8 * * *'

jobs:
  convert-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Run Plain2srs Docker Container
        run: |
          docker run --name plain2srs-container \
            -v "${{ github.workspace }}:/workspace" \
            itdoginfo/plain2srs-action:20241216 \
            -i /workspace/Russia/inside-raw.lst \
            -o russia-inside \
            -c
          docker cp plain2srs-container:/app/plain2srs/output/russia-inside.srs ${{ github.workspace }}/russia-inside.srs

      - name: Remove tag
        run: git tag -d latest && git push origin --delete latest

      - name: Release
        uses: softprops/action-gh-release@v2.2.0
        with:
          files: "${{ github.workspace }}/russia-inside.srs"
          tag_name: latest